package pe.egcc.cursoapp.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.egcc.cursoapp.controller.NotasController;
import pe.egcc.cursoapp.dto.EstadisticaDto;

/**
 *
 * @author Gustavo Coronel
 * @blog gcoronelc.blogspot.com
 * @email gcoronelc@gmail.com
 */
public class EstadisticaView extends javax.swing.JDialog {

   /**
    * Creates new form EstadisticaView
    */
   public EstadisticaView(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();
      obtenerEstadistica();
   }

   private void obtenerEstadistica() {
      try {
         // Obtener estadistica
         NotasController control = new NotasController();
         EstadisticaDto[] listado = control.obtenerEstadistica();
         // Mostrar Listado
         DefaultTableModel tabla;
         tabla = (DefaultTableModel) tblRepo.getModel();
         tabla.setRowCount(0);
         for (EstadisticaDto dto : listado) {
            Object[] rowData = {
               dto.getConcepto(),
               dto.getValor()
            };
            tabla.addRow(rowData);
         }
      } catch (Exception e) {
         JOptionPane.showMessageDialog(
                 rootPane,
                 e.getMessage(),
                 "NOTAS - ERROR",
                 JOptionPane.ERROR_MESSAGE
         );
      }
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      tblRepo = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("ESTADISTICA");

      tblRepo.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null},
            {null, null},
            {null, null},
            {null, null}
         },
         new String [] {
            "CONCEPTO", "VALOR"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.Integer.class
         };
         boolean[] canEdit = new boolean [] {
            true, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tblRepo.setColumnSelectionAllowed(true);
      jScrollPane1.setViewportView(tblRepo);
      tblRepo.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      if (tblRepo.getColumnModel().getColumnCount() > 0) {
         tblRepo.getColumnModel().getColumn(0).setResizable(false);
         tblRepo.getColumnModel().getColumn(1).setResizable(false);
      }

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(EstadisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(EstadisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(EstadisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(EstadisticaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the dialog */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            EstadisticaView dialog = new EstadisticaView(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
               @Override
               public void windowClosing(java.awt.event.WindowEvent e) {
                  System.exit(0);
               }
            });
            dialog.setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblRepo;
   // End of variables declaration//GEN-END:variables

}
