package pe.egcc.ventaapp.view;

import java.util.List;
import pe.egcc.ventaapp.controller.VentaController;
import pe.egcc.ventaapp.dto.ProductoDto;
import pe.egcc.ventaapp.dto.VentaDto;

/**
 *
 * @author Gustavo Coronel
 * @blog   gcoronelc.blogspot.com
 * @email  gcoronelc@gmail.com
 */
public class RegistrarVenta extends javax.swing.JFrame {
   
   private VentaController ventaController;
   private boolean estoyTrabajando;

    /** Creates new form RegistrarVenta */
    public RegistrarVenta() {
        initComponents();
        estoyTrabajando = false;
        ventaController = new VentaController();
        llenarComboCategorias();
        this.setLocationRelativeTo(null);
    }
    
    private void llenarComboCategorias(){
       // Obtener los datos
       List<String> categorias = ventaController.getCategorias();
       // Proceso
       estoyTrabajando = true;
       cboCategoria.removeAllItems();
       for (String categoria : categorias) {
          cboCategoria.addItem(categoria);
       }
       cboCategoria.setSelectedIndex(-1);
       estoyTrabajando = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      cboCategoria = new javax.swing.JComboBox<>();
      jLabel2 = new javax.swing.JLabel();
      cboProducto = new javax.swing.JComboBox<>();
      jLabel3 = new javax.swing.JLabel();
      txtPrecio = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      txtCantidad = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      btnRegistrarVenta = new javax.swing.JButton();
      btnSalir = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      btnListadoVentas = new javax.swing.JButton();
      btnResumenCategoria = new javax.swing.JButton();
      btnResumenProducto = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("VENTAS APP");

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N

      jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel1.setText("Categoría:");

      cboCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      cboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      cboCategoria.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboCategoriaActionPerformed(evt);
         }
      });

      jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel2.setText("Producto:");

      cboProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      cboProducto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cboProductoActionPerformed(evt);
         }
      });

      jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel3.setText("Precio:");

      txtPrecio.setEditable(false);
      txtPrecio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      txtPrecio.setDisabledTextColor(new java.awt.Color(102, 102, 102));
      txtPrecio.setEnabled(false);

      jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
      jLabel4.setText("Cantidad:");

      txtCantidad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtPrecio))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtCantidad)))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(cboCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(cboProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(21, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N

      btnRegistrarVenta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      btnRegistrarVenta.setText("Registrar Venta");
      btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRegistrarVentaActionPerformed(evt);
         }
      });

      btnSalir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      btnSalir.setText("Salir");
      btnSalir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalirActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(25, Short.MAX_VALUE))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPORTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N

      btnListadoVentas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      btnListadoVentas.setText("Listado Ventas");
      btnListadoVentas.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnListadoVentasActionPerformed(evt);
         }
      });

      btnResumenCategoria.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      btnResumenCategoria.setText("Resumen Cat.");
      btnResumenCategoria.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnResumenCategoriaActionPerformed(evt);
         }
      });

      btnResumenProducto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      btnResumenProducto.setText("Resumen Prod.");
      btnResumenProducto.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnResumenProductoActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(24, 24, 24)
            .addComponent(btnListadoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(btnResumenCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(btnResumenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnListadoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnResumenCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnResumenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 0, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
      // Valiadación
      if( estoyTrabajando ){
         return;
      }
      if( cboCategoria.getSelectedIndex() == -1){
         return;
      }
      // Datos
      String categoria = cboCategoria.getSelectedItem().toString();
      List<ProductoDto> productos = ventaController.getProductos( categoria );
      // Proceso
      estoyTrabajando = true;
      cboProducto.removeAllItems();
      for (ProductoDto producto : productos) {
         cboProducto.addItem(producto);
      }
      cboProducto.setSelectedIndex(-1);
      txtPrecio.setText("");
      estoyTrabajando = false;
   }//GEN-LAST:event_cboCategoriaActionPerformed

   private void cboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProductoActionPerformed
      // Validación
      if( estoyTrabajando ){
         return;
      }
      if( cboProducto.getSelectedIndex() == -1 ){
         return;
      }
      // Proceso
      ProductoDto dto = (ProductoDto) cboProducto.getSelectedItem();
      txtPrecio.setText(dto.getPrecio().toString());
   }//GEN-LAST:event_cboProductoActionPerformed

   private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
      // Datos
      VentaDto ventaDto = new VentaDto();
      ProductoDto producto = (ProductoDto) cboProducto.getSelectedItem();
      ventaDto.setCategoria(producto.getCategoria());
      ventaDto.setProducto(producto.getProducto());
      ventaDto.setPrecio(producto.getPrecio());
      ventaDto.setCantidad(Integer.parseInt(txtCantidad.getText()));
      // Proceso
      ventaController.registrarVenta(ventaDto);
      // Limpiar el formulario
      estoyTrabajando = true;
      cboCategoria.setSelectedIndex(-1);
      cboProducto.setSelectedIndex(-1);
      txtPrecio.setText("");
      txtCantidad.setText("");
      estoyTrabajando = false;
   }//GEN-LAST:event_btnRegistrarVentaActionPerformed

   private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      System.exit(0);
   }//GEN-LAST:event_btnSalirActionPerformed

   private void btnListadoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoVentasActionPerformed
      RepoListadoVentas view = new RepoListadoVentas(null, true);
      view.setVisible(true);
   }//GEN-LAST:event_btnListadoVentasActionPerformed

   private void btnResumenCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenCategoriaActionPerformed
      RepoResumenCategoria view = new RepoResumenCategoria(null, true);
      view.setVisible(true);
   }//GEN-LAST:event_btnResumenCategoriaActionPerformed

   private void btnResumenProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumenProductoActionPerformed
      RepoResumenProducto view = new RepoResumenProducto(null, true);
      view.setVisible(true);
   }//GEN-LAST:event_btnResumenProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVenta().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnListadoVentas;
   private javax.swing.JButton btnRegistrarVenta;
   private javax.swing.JButton btnResumenCategoria;
   private javax.swing.JButton btnResumenProducto;
   private javax.swing.JButton btnSalir;
   private javax.swing.JComboBox<String> cboCategoria;
   private javax.swing.JComboBox<ProductoDto> cboProducto;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JTextField txtCantidad;
   private javax.swing.JTextField txtPrecio;
   // End of variables declaration//GEN-END:variables

}
